package com.dhxa.bizcloud.microservice.entity;

// Generated 2017-8-16 14:10:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TaDataDic generated by hbm2java
 */
public class DataDic implements java.io.Serializable {

	private BigDecimal id;
	private String code;
	private String codeText;
	private String PCode;
	private Boolean isdelete;
	private String PCodeText;
	private String updateDt;
	private BigDecimal updateUser;

	public DataDic() {
	}

	public DataDic(BigDecimal id) {
		this.id = id;
	}

	public DataDic(BigDecimal id, String code, String codeText, String PCode,
			Boolean isdelete, String PCodeText, String updateDt,
			BigDecimal updateUser) {
		this.id = id;
		this.code = code;
		this.codeText = codeText;
		this.PCode = PCode;
		this.isdelete = isdelete;
		this.PCodeText = PCodeText;
		this.updateDt = updateDt;
		this.updateUser = updateUser;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getCodeText() {
		return this.codeText;
	}

	public void setCodeText(String codeText) {
		this.codeText = codeText;
	}

	public String getPCode() {
		return this.PCode;
	}

	public void setPCode(String PCode) {
		this.PCode = PCode;
	}

	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	public String getPCodeText() {
		return this.PCodeText;
	}

	public void setPCodeText(String PCodeText) {
		this.PCodeText = PCodeText;
	}

	public String getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(String updateDt) {
		this.updateDt = updateDt;
	}

	public BigDecimal getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(BigDecimal updateUser) {
		this.updateUser = updateUser;
	}

}
