package com.dhxa.bizcloud.microservice.entity;

// Generated 2017-8-16 14:10:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TaDept generated by hbm2java
 */
public class Dept implements java.io.Serializable {

	private BigDecimal id;
	private String deptName;
	private String province;
	private String city;
	private String county;
	private String createTime;
	private BigDecimal creator;
	private String isdelete;
	private BigDecimal higherDeptId;
	private String email;

	public Dept() {
	}

	public Dept(BigDecimal id) {
		this.id = id;
	}

	public Dept(BigDecimal id, String deptName, String province, String city,
			String county, String createTime, BigDecimal creator,
			String isdelete, BigDecimal higherDeptId, String email) {
		this.id = id;
		this.deptName = deptName;
		this.province = province;
		this.city = city;
		this.county = county;
		this.createTime = createTime;
		this.creator = creator;
		this.isdelete = isdelete;
		this.higherDeptId = higherDeptId;
		this.email = email;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public BigDecimal getCreator() {
		return this.creator;
	}

	public void setCreator(BigDecimal creator) {
		this.creator = creator;
	}

	public String getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(String isdelete) {
		this.isdelete = isdelete;
	}

	public BigDecimal getHigherDeptId() {
		return this.higherDeptId;
	}

	public void setHigherDeptId(BigDecimal higherDeptId) {
		this.higherDeptId = higherDeptId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
