package com.dhxa.bizcloud.microservice.entity;

// Generated 2017-8-16 14:10:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TaRole generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private BigDecimal id;
	private String roleName;
	private Boolean isdelete;

	public Role() {
	}

	public Role(BigDecimal id) {
		this.id = id;
	}

	public Role(BigDecimal id, String roleName, Boolean isdelete) {
		this.id = id;
		this.roleName = roleName;
		this.isdelete = isdelete;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

}
