package com.dhxa.bizcloud.microservice.entity;

// Generated 2017-8-16 14:10:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TaUserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal userid;
	private BigDecimal roleId;
	private BigDecimal isdelete;

	public UserRole() {
	}

	public UserRole(BigDecimal id) {
		this.id = id;
	}

	public UserRole(BigDecimal id, BigDecimal userid, BigDecimal roleId,
			BigDecimal isdelete) {
		this.id = id;
		this.userid = userid;
		this.roleId = roleId;
		this.isdelete = isdelete;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public BigDecimal getUserid() {
		return this.userid;
	}

	public void setUserid(BigDecimal userid) {
		this.userid = userid;
	}

	public BigDecimal getRoleId() {
		return this.roleId;
	}

	public void setRoleId(BigDecimal roleId) {
		this.roleId = roleId;
	}

	public BigDecimal getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(BigDecimal isdelete) {
		this.isdelete = isdelete;
	}

}
