module.exports = [
    {
      "id": "1",
      "acceptNumber": "国铁许受字〔2017〕第 59 号",
      "applyItems": "铁路机车车辆维修许可",
      "companyName": "中车兰州机车有限公司",
      "employeeInfo": "周颜忠",
      "acceptInstitution": "c30",
      "acceptBasis": "c40",
      "acceptTime": "2017年08月22日",
      "acceptWorker": "杨葱",
      "acceptState":"审核中",
      "suggestion":"",
      "reviewResult":"审核通过",
    },
    {
      "id": "2",
      "acceptNumber": "c082141134302",
      "applyItems": "货车SZW",
      "companyName": "中车沈阳机车车辆有限公司",
      "employeeInfo": "c20",
      "acceptInstitution": "c30",
      "acceptBasis": "c40",
      "acceptTime": "c30",
      "acceptWorker": "c40",
      "acceptState":"审核中",
      "suggestion":"",
      "reviewResult":"审核通过"
    },
    {
      "id": "3",
      "acceptNumber": "c082141134303",
      "applyItems": "铁路救援起重机ZW",
      "companyName": "中车大连机车车辆有限公司",
      "employeeInfo": "c20",
      "acceptInstitution": "c30",
      "acceptBasis": "c40",
      "acceptTime": "c30",
      "acceptWorker": "c40",
      "acceptState":"审核中",
      "reviewResult":"审核通过"
    },
    {
      "id": "4",
      "acceptNumber": "c082141134304",
      "applyItems": "客车SZW，铺轨机和架桥机（组）车辆ZW",
      "companyName": "中铁山桥集团有限公司",
      "employeeInfo": "c20",
      "acceptInstitution": "c30",
      "acceptBasis": "c40",
      "acceptTime": "c30",
      "acceptWorker": "c40",
      "acceptState":"审核中",
      "suggestion":"",
      "reviewResult":"审核通过"
    },
    {
      "id": "5",
      "acceptNumber": "c082141134305",
      "applyItems": "机车W",
      "companyName": "中车长江车辆有限公司（常州分公司）",
      "employeeInfo": "c20",
      "acceptInstitution": "c30",
      "acceptBasis": "c40",
      "acceptTime": "c30",
      "acceptWorker": "c40",
      "acceptState":"审核中",
      "suggestion":"",
      "reviewResult":"审核通过"
    },
    {
      "id": "6",
      "acceptNumber": "c082141134306",
      "applyItems": "机车W",
      "companyName": "中车成都机车车辆有限公司",
      "employeeInfo": "c20",
      "acceptInstitution": "c30",
      "acceptBasis": "c40",
      "acceptTime": "c30",
      "acceptWorker": "c40",
      "acceptState":"审核中",
      "suggestion":"",
      "reviewResult":"审核通过"
    },
    {
      "id": "7",
      "acceptNumber": "c082141134307",
      "applyItems": "机车W",
      "companyName": "资阳中车电力机车有限公司",
      "employeeInfo": "c20",
      "acceptInstitution": "c30",
      "acceptBasis": "c40",
      "acceptTime": "c30",
      "acceptWorker": "c40",
      "acceptState":"审核中",
      "suggestion":"",
      "reviewResult":"审核通过"
    },
    {
      "id": "8",
      "acceptNumber": "c082141134308",
      "applyItems": "货车W",
      "companyName": "中国铁建高新装备股份有限公司",
      "employeeInfo": "c20",
      "acceptInstitution": "c30",
      "acceptBasis": "c40",
      "acceptTime": "c30",
      "acceptWorker": "c40",
      "acceptState":"审核中",
      "suggestion":"",
      "reviewResult":"审核通过"
    },
    {
      "id": "9",
      "acceptNumber": "c082141134309",
      "applyItems": "铁路救援起重机SZW",
      "companyName": "新乡万通铁路车辆修配厂",
      "employeeInfo": "c20",
      "acceptInstitution": "c30",
      "acceptBasis": "c40",
      "acceptTime": "c30",
      "acceptWorker": "c40",
      "acceptState":"审核中",
      "reviewResult":"审核通过"
    }
]
