package com.dhxa.bizcloud.appservice.entity;

// Generated 2017-8-16 14:10:10 by Hibernate Tools 3.4.0.CR1


/**
 * TaUser generated by hbm2java
 */

public class User implements java.io.Serializable {

	
	private Long userid;
	private String username;
	private String password;
	private String headimgurl;
	private String isdelete;
	private String truename;	
	private Long deptId;
	private String phone;
	private String email;

	public User() {
	}

	public User(Long userid) {
		this.userid = userid;
	}

	public User(Long userid, String username, String password,
			String headimgurl, String isdelete, String truename,
			Long deptId, String phone, String email) {
		this.userid = userid;
		this.username = username;
		this.password = password;
		this.headimgurl = headimgurl;
		this.isdelete = isdelete;
		this.truename = truename;
		this.deptId = deptId;
		this.phone = phone;
		this.email = email;
	}

	public Long getUserid() {
		return this.userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getHeadimgurl() {
		return this.headimgurl;
	}

	public void setHeadimgurl(String headimgurl) {
		this.headimgurl = headimgurl;
	}

	public String getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(String isdelete) {
		this.isdelete = isdelete;
	}

	public String getTruename() {
		return this.truename;
	}

	public void setTruename(String truename) {
		this.truename = truename;
	}

	public Long getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Long deptId) {
		this.deptId = deptId;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
